#!/bin/bash

# requires $real_tar_binary env pointing to the real, not-wrapper, tar program
# normally should have $FAKETIME_TIME env set

if [[ ! -z $FAKETIME_TIME ]] ; then
	# export TAR_OPTIONS="--mtime $TIMESTAMP_RFC3339 --sort-input --owner root --group root --numeric-owner" # tip: spaces in args values NOT allowed unless escaped
	$real_tar_binary "$@" --mtime "$FAKETIME_TIME" --sort-input --owner root --group root --numeric-owner
	exit $?
else
	$real_tar_binary "$@"
	exit 1

fi

echo "ERROR: end of code too early ($0)"

