# place for STATIC settings for release. [autogenerated] 
export kernel_general_version="3.2.69" # base version (should match the one is sourcecode.list)
export KERNEL_DATE='2015-08-02 00:16:17' # UTC time of mempo version. This is > then max(kernel,grsec,patches) times
export CURRENT_SEED='1184c4861ddd73b5adb31adf2ccd02251f80958d3c8a13461e234667edb94e62' #  block 826275 (*)
export DEBIAN_REVISION='001' # see README.md how to update it on git tag, on rc and final releases
