# place for STATIC settings for release. [autogenerated] 
export kernel_general_version="3.2.63" # base version (should match the one is sources.list)
export KERNEL_DATE='2014-10-28 04:17:34' # UTC time of mempo version. This is > then max(kernel,grsec,patches) times
export CURRENT_SEED='4f5777d82e8ee5d31ade5f2abd2dbbf64c99b3dad0bf555545d49be3634dc4e8' # litecoin block 666011 (*)
export DEBIAN_REVISION='02' # see README.md how to update it on git tag, on rc and final releases
