# place for STATIC settings for release. [autogenerated] 
export kernel_general_version="3.2.69" # base version (should match the one is sourcecode.list)
export KERNEL_DATE='2015-06-24 12:29:59' # UTC time of mempo version. This is > then max(kernel,grsec,patches) times
export CURRENT_SEED='91cb424386f14ae38fc8783a31f0b9ce291c4d4e14d8a9b267964b22fcfc9754' #  block 803784 (*)
export DEBIAN_REVISION='001' # see README.md how to update it on git tag, on rc and final releases
